package db.migration;

import org.flywaydb.core.api.migration.BaseJavaMigration;
import org.flywaydb.core.api.migration.Context;

import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;

/**
 * V8: Avanza la identidad (SERIAL / GENERATED BY DEFAULT AS IDENTITY) de todas las
 * tablas sembradas con ids explícitos en V1-V7. H2 y PostgreSQL NO avanzan la secuencia
 * cuando se insertan ids explícitos, por lo que sin este paso el siguiente INSERT de la
 * aplicación (p. ej. registrar un usuario nuevo) colisionaría con la clave primaria.
 */
public class V8__Advance_Sequences extends BaseJavaMigration {

    private static final String[] SEEDED_TABLES = {
            "usuarios", "roles", "usuario_roles", "especialidades", "profesionales",
            "sesiones_terapia", "categorias_recursos", "recurso_digital", "foros_tematicos",
            "foro_temas", "foro_respuestas", "diario_emocional"
    };

    @Override
    public void migrate(Context context) throws Exception {
        Connection connection = context.getConnection();
        DatabaseMetaData meta = connection.getMetaData();
        boolean postgres = meta.getDatabaseProductName().toLowerCase().contains("postgres");

        for (String table : SEEDED_TABLES) {
            if (postgres) {
                advancePostgres(connection, table);
            } else {
                advanceH2(connection, table);
            }
        }
    }

    private void advanceH2(Connection connection, String table) throws Exception {
        try (Statement statement = connection.createStatement()) {
            statement.executeUpdate(
                    "ALTER TABLE " + table + " ALTER COLUMN id RESTART WITH " +
                            "(SELECT COALESCE(MAX(id), 0) + 1 FROM " + table + ")");
        }
    }

    private void advancePostgres(Connection connection, String table) throws Exception {
        String sequence = null;
        try (PreparedStatement ps = connection.prepareStatement(
                "SELECT pg_get_serial_sequence('public." + table + "', 'id')")) {
            try (ResultSet rs = ps.executeQuery()) {
                if (rs.next()) {
                    sequence = rs.getString(1);
                }
            }
        }
        if (sequence == null) {
            return;
        }
        try (PreparedStatement ps = connection.prepareStatement(
                "SELECT setval(?, (SELECT COALESCE(MAX(id), 1) FROM " + table + "))")) {
            ps.setString(1, sequence);
            ps.executeQuery();
        }
    }
}
