-- ============================================================================
-- AbrazaMente - Esquema PostgreSQL consolidado
-- Migración no destructiva desde MySQL
-- IMPORTANTE: este script NO elimina ni sobrescribe la base MySQL original.
-- Ejecutar sobre una base PostgreSQL vacía creada previamente con codificación UTF-8.
-- ============================================================================

BEGIN;

SET client_encoding = 'UTF8';
SET TIME ZONE 'UTC';
SET search_path TO public;

-- ============================================================================
-- TABLA: ROLES
-- ============================================================================
CREATE TABLE IF NOT EXISTS roles (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL UNIQUE,
    descripcion TEXT,
    permisos_json JSONB,
    estado VARCHAR(20) CHECK (estado IN ('activo', 'inactivo')) DEFAULT 'activo',
    fecha_creacion TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================================
-- TABLA: USUARIOS
-- ============================================================================
CREATE TABLE IF NOT EXISTS usuarios (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    run VARCHAR (255) NOT NULL,
    nombres VARCHAR(100) NOT NULL,
    apellidos VARCHAR(100) NOT NULL,
    fecha_nacimiento DATE,
    genero VARCHAR(20) CHECK (genero IN ('masculino', 'femenino', 'otro', 'prefiero_no_decir')),
    estado_civil VARCHAR(50),
    ciudad VARCHAR(100),
    telefono VARCHAR(20),
    bio TEXT,
    estado VARCHAR(20) CHECK (estado IN ('activo', 'inactivo', 'suspendido')) DEFAULT 'activo',
    fecha_creacion TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    fecha_ultimo_login TIMESTAMPTZ
);

-- ============================================================================
-- TABLA: USUARIO_ROLES
-- ============================================================================
CREATE TABLE IF NOT EXISTS usuario_roles (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id INTEGER NOT NULL,
    rol_id INTEGER NOT NULL,
    fecha_asignacion TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_usuario_rol UNIQUE (usuario_id, rol_id),
    FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (rol_id) REFERENCES roles(id) ON DELETE CASCADE ON UPDATE CASCADE
);

-- ============================================================================
-- TABLA: DATOS_INICIALES_USUARIO
-- ============================================================================
CREATE TABLE IF NOT EXISTS datos_iniciales_usuario (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id INTEGER NOT NULL UNIQUE,
    tiene_estres BOOLEAN DEFAULT FALSE,
    tiene_tristeza BOOLEAN DEFAULT FALSE,
    se_siente_desorientado BOOLEAN DEFAULT FALSE,
    trabaja_actualmente BOOLEAN DEFAULT FALSE,
    tiene_red_apoyo BOOLEAN DEFAULT FALSE,
    notas_adicionales TEXT,
    fecha_registro TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE ON UPDATE CASCADE
);

-- ============================================================================
-- TABLA: ESPECIALIDADES
-- ============================================================================
CREATE TABLE IF NOT EXISTS especialidades (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(150) NOT NULL UNIQUE,
    descripcion TEXT
);

-- ============================================================================
-- TABLA: PROFESIONALES
-- ============================================================================
CREATE TABLE IF NOT EXISTS profesionales (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id INTEGER NOT NULL UNIQUE,
    licencia_profesional VARCHAR(255),
    especialidad_principal_id INTEGER,
    descripcion_profesional TEXT,
    es_voluntario BOOLEAN DEFAULT FALSE,
    tarifa_sesion DECIMAL(10,2),
    biografia_profesional TEXT,
    anos_experiencia INTEGER,
    idiomas VARCHAR(255),
    estado VARCHAR(20) CHECK (estado IN ('activo', 'inactivo', 'suspendido')) DEFAULT 'activo',
    fecha_registro TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (especialidad_principal_id) REFERENCES especialidades(id) ON DELETE SET NULL ON UPDATE CASCADE
);

-- ============================================================================
-- TABLA: DISPONIBILIDAD
-- Descripción: Disponibilidad para usuarios y profesionales
-- ============================================================================
CREATE TABLE IF NOT EXISTS disponibilidad (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id INTEGER,
    profesional_id INTEGER,
    dia_semana VARCHAR(20) CHECK (dia_semana IN ('lunes', 'martes', 'miercoles', 'jueves', 'viernes', 'sabado', 'domingo')),
    hora_inicio TIME,
    hora_fin TIME,
    es_activa BOOLEAN DEFAULT TRUE,
    tipo_sesion VARCHAR(20) CHECK (tipo_sesion IN ('online', 'presencial', 'ambas')) DEFAULT 'ambas',
    FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (profesional_id) REFERENCES profesionales(id) ON DELETE CASCADE ON UPDATE CASCADE
);

-- ============================================================================
-- TABLA: PROBLEMAS_EMOCIONALES
-- ============================================================================
CREATE TABLE IF NOT EXISTS problemas_emocionales (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(150) NOT NULL UNIQUE,
    descripcion TEXT,
    estado VARCHAR(20) CHECK (estado IN ('activo', 'inactivo')) DEFAULT 'activo'
);

-- ============================================================================
-- TABLA: PERSONAJES
-- ============================================================================
CREATE TABLE IF NOT EXISTS personajes (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL,
    origen VARCHAR(255),
    tipo_personaje VARCHAR(20) CHECK (tipo_personaje IN ('ficticio', 'historico', 'celebridad', 'serie', 'anime', 'videojuego')),
    descripcion TEXT,
    historia_superacion TEXT,
    imagen_url VARCHAR(500),
    datos_fandom_json JSONB,
    analisis_ia JSONB,
    estado VARCHAR(20) CHECK (estado IN ('activo', 'inactivo')) DEFAULT 'activo',
    fecha_creacion TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================================
-- TABLA: PERSONAJE_PROBLEMA
-- ============================================================================
CREATE TABLE IF NOT EXISTS personaje_problema (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    personaje_id INTEGER NOT NULL,
    problema_id INTEGER NOT NULL,
    descripcion TEXT,
    CONSTRAINT uk_personaje_problema UNIQUE (personaje_id, problema_id),
    FOREIGN KEY (personaje_id) REFERENCES personajes(id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (problema_id) REFERENCES problemas_emocionales(id) ON DELETE CASCADE ON UPDATE CASCADE
);

-- ============================================================================
-- TABLA: DIARIO_EMOCIONAL
-- ============================================================================
CREATE TABLE IF NOT EXISTS diario_emocional (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id INTEGER NOT NULL,
    fecha_entrada DATE NOT NULL,
    contenido TEXT NOT NULL,
    estado_privacidad VARCHAR(20) CHECK (estado_privacidad IN ('privado', 'profesional', 'compartido')) DEFAULT 'privado',
    acceso_profesionales JSONB,
    creado_en TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    actualizado_en TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT uk_usuario_fecha UNIQUE (usuario_id, fecha_entrada)
);

-- ============================================================================
-- TABLA: EMOCION_DIA
-- ============================================================================
CREATE TABLE IF NOT EXISTS emocion_dia (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    diario_id INTEGER NOT NULL,
    personaje_id INTEGER,
    intensidad SMALLINT,
    notas TEXT,
    FOREIGN KEY (diario_id) REFERENCES diario_emocional(id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (personaje_id) REFERENCES personajes(id) ON DELETE SET NULL ON UPDATE CASCADE
);

-- ============================================================================
-- TABLA: CATEGORIAS_RECURSOS
-- ============================================================================
CREATE TABLE IF NOT EXISTS categorias_recursos (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(150) NOT NULL UNIQUE,
    descripcion TEXT,
    icono_url VARCHAR(500)
);

-- ============================================================================
-- TABLA: RECURSOS_DIGITALES
-- ============================================================================
CREATE TABLE IF NOT EXISTS recursos_digitales (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR(255) NOT NULL,
    descripcion TEXT,
    tipo_contenido VARCHAR(20) CHECK (tipo_contenido IN ('articulo', 'video', 'podcast', 'libro', 'documento', 'infografia', 'otro')),
    autor VARCHAR(255),
    url_contenido VARCHAR(500),
    duracion_minutos INTEGER,
    imagen_portada_url VARCHAR(500),
    es_premium BOOLEAN DEFAULT FALSE,
    precio DECIMAL(10,2),
    codigo_afiliado VARCHAR(100),
    url_afiliado VARCHAR(500),
    vistas INTEGER DEFAULT 0,
    estado VARCHAR(20) CHECK (estado IN ('activo', 'inactivo', 'eliminado')) DEFAULT 'activo',
    fecha_creacion TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================================
-- TABLA: RECURSO_CATEGORIA
-- ============================================================================
CREATE TABLE IF NOT EXISTS recurso_categoria (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recurso_id INTEGER NOT NULL,
    categoria_id INTEGER NOT NULL,
    CONSTRAINT uk_recurso_categoria UNIQUE (recurso_id, categoria_id),
    FOREIGN KEY (recurso_id) REFERENCES recursos_digitales(id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (categoria_id) REFERENCES categorias_recursos(id) ON DELETE CASCADE ON UPDATE CASCADE
);

-- ============================================================================
-- TABLA: RECURSOS_DESCARGADOS
-- ============================================================================
CREATE TABLE IF NOT EXISTS recursos_descargados (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id INTEGER NOT NULL,
    recurso_id INTEGER NOT NULL,
    fecha_descarga TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_usuario_recurso UNIQUE (usuario_id, recurso_id),
    FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (recurso_id) REFERENCES recursos_digitales(id) ON DELETE CASCADE ON UPDATE CASCADE
);

-- ============================================================================
-- TABLA: PROFESIONAL_ESPECIALIDAD
-- ============================================================================
CREATE TABLE IF NOT EXISTS profesional_especialidad (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profesional_id INTEGER NOT NULL,
    especialidad_id INTEGER NOT NULL,
    nivel_expertise VARCHAR(20) CHECK (nivel_expertise IN ('basico', 'intermedio', 'avanzado', 'experto')) DEFAULT 'intermedio',
    CONSTRAINT uk_profesional_especialidad UNIQUE (profesional_id, especialidad_id),
    FOREIGN KEY (profesional_id) REFERENCES profesionales(id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (especialidad_id) REFERENCES especialidades(id) ON DELETE CASCADE ON UPDATE CASCADE
);

-- ============================================================================
-- TABLA: SESIONES_MEDICAS
-- Descripción: Sesiones de telemedicina y medicina integrada
-- ============================================================================
CREATE TABLE IF NOT EXISTS sesiones_medicas (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id INTEGER NOT NULL,
    profesional_id INTEGER NOT NULL,
    fecha_sesion TIMESTAMPTZ NOT NULL,
    duracion_minutos INTEGER DEFAULT 45,
    tipo_sesion VARCHAR(20) CHECK (tipo_sesion IN ('online', 'presencial')) DEFAULT 'online',
    estado_sesion VARCHAR(20) CHECK (estado_sesion IN ('programada', 'en_progreso', 'completada', 'cancelada', 'no_asistio')) DEFAULT 'programada',
    url_videollamada VARCHAR(500),
    token_videollamada VARCHAR(500),
    archivo_grabacion VARCHAR(500),
    consentimiento_grabacion BOOLEAN DEFAULT FALSE,
    monto_pagado DECIMAL(10,2),
    notas_clinicas TEXT,
    diagnostico_preliminar TEXT,
    recomendaciones TEXT,
    proxima_sesion TIMESTAMPTZ,
    fecha_creacion TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (profesional_id) REFERENCES profesionales(id) ON DELETE RESTRICT ON UPDATE CASCADE
);

-- ============================================================================
-- TABLA: VALORACIONES_PROFESIONAL
-- Descripción: Reseñas y valoraciones con comentarios
-- ============================================================================
CREATE TABLE IF NOT EXISTS valoraciones_profesional (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sesion_medica_id INTEGER,
    usuario_id INTEGER NOT NULL,
    profesional_id INTEGER NOT NULL,
    puntuacion DECIMAL(3,2) NOT NULL,
    comentario TEXT,
    aspectos_positivos TEXT,
    aspectos_mejora TEXT,
    recomendaria BOOLEAN DEFAULT TRUE,
    fecha_valoracion TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (sesion_medica_id) REFERENCES sesiones_medicas(id) ON DELETE SET NULL ON UPDATE CASCADE,
    FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (profesional_id) REFERENCES profesionales(id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT uk_usuario_profesional_fecha UNIQUE (usuario_id, profesional_id, fecha_valoracion)
);

-- ============================================================================
-- TABLA: LOGROS
-- ============================================================================
CREATE TABLE IF NOT EXISTS logros (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(150) NOT NULL UNIQUE,
    descripcion TEXT,
    tipo_logro VARCHAR(20) CHECK (tipo_logro IN ('registro', 'participacion', 'taller', 'recursos', 'objetivos', 'social')),
    puntos INTEGER DEFAULT 0,
    icono_url VARCHAR(500),
    condicion_logro JSONB,
    estado VARCHAR(20) CHECK (estado IN ('activo', 'inactivo')) DEFAULT 'activo'
);

-- ============================================================================
-- TABLA: USUARIO_LOGROS
-- ============================================================================
CREATE TABLE IF NOT EXISTS usuario_logros (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id INTEGER NOT NULL,
    logro_id INTEGER NOT NULL,
    fecha_desbloqueado TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_usuario_logro UNIQUE (usuario_id, logro_id),
    FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (logro_id) REFERENCES logros(id) ON DELETE CASCADE ON UPDATE CASCADE
);

-- ============================================================================
-- TABLA: FOROS_TEMATICOS
-- ============================================================================
CREATE TABLE IF NOT EXISTS foros_tematicos (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(150) NOT NULL UNIQUE,
    descripcion TEXT,
    categoria VARCHAR(100),
    reglas_moderacion TEXT,
    estado VARCHAR(20) CHECK (estado IN ('activo', 'inactivo', 'suspendido')) DEFAULT 'activo',
    numero_miembros INTEGER DEFAULT 0,
    fecha_creacion TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================================
-- TABLA: FORO_TEMAS
-- ============================================================================
CREATE TABLE IF NOT EXISTS foro_temas (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    forum_id INTEGER NOT NULL,
    usuario_id INTEGER NOT NULL,
    titulo VARCHAR(255) NOT NULL,
    contenido TEXT,
    numero_respuestas INTEGER DEFAULT 0,
    vistas INTEGER DEFAULT 0,
    fecha_creacion TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    fecha_ultima_actividad TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (forum_id) REFERENCES foros_tematicos(id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE ON UPDATE CASCADE
);

-- ============================================================================
-- TABLA: FORO_RESPUESTAS
-- ============================================================================
CREATE TABLE IF NOT EXISTS foro_respuestas (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tema_id INTEGER NOT NULL,
    usuario_id INTEGER NOT NULL,
    contenido TEXT NOT NULL,
    es_solucion BOOLEAN DEFAULT FALSE,
    numero_votos_positivos INTEGER DEFAULT 0,
    fecha_creacion TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (tema_id) REFERENCES foro_temas(id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE ON UPDATE CASCADE
);

-- ============================================================================
-- TABLA: MODERADORES
-- ============================================================================
CREATE TABLE IF NOT EXISTS moderadores (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id INTEGER NOT NULL,
    forum_id INTEGER NOT NULL,
    nivel_moderacion VARCHAR(20) CHECK (nivel_moderacion IN ('basico', 'avanzado', 'supervisor')) DEFAULT 'basico',
    fecha_asignacion TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_usuario_forum UNIQUE (usuario_id, forum_id),
    FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (forum_id) REFERENCES foros_tematicos(id) ON DELETE CASCADE ON UPDATE CASCADE
);

-- ============================================================================
-- TABLA: REPORTES_CONTENIDO
-- ============================================================================
CREATE TABLE IF NOT EXISTS reportes_contenido (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id INTEGER NOT NULL,
    tipo_contenido VARCHAR(20) CHECK (tipo_contenido IN ('post', 'comentario', 'tema_foro', 'respuesta_foro')),
    contenido_id INTEGER NOT NULL,
    motivo VARCHAR(20) CHECK (motivo IN ('ofensivo', 'spam', 'acoso', 'falso_danino', 'otro')),
    descripcion TEXT,
    estado VARCHAR(20) CHECK (estado IN ('pendiente', 'revisar', 'resuelto', 'desestimado')) DEFAULT 'pendiente',
    fecha_reporte TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE ON UPDATE CASCADE
);

-- ============================================================================
-- TABLA: TALLERES_GRUPALES
-- ============================================================================
CREATE TABLE IF NOT EXISTS talleres_grupales (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR(255) NOT NULL,
    descripcion TEXT,
    instructor_id INTEGER,
    tipo_taller VARCHAR(20) CHECK (tipo_taller IN ('online', 'presencial', 'hibrido')) DEFAULT 'online',
    es_gratuito BOOLEAN DEFAULT FALSE,
    precio DECIMAL(10,2),
    max_participantes INTEGER,
    duracion_total_horas INTEGER,
    estado VARCHAR(20) CHECK (estado IN ('planificado', 'en_curso', 'completado', 'cancelado')) DEFAULT 'planificado',
    fecha_inicio DATE,
    fecha_fin DATE,
    fecha_creacion TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (instructor_id) REFERENCES profesionales(id) ON DELETE SET NULL ON UPDATE CASCADE
);

-- ============================================================================
-- TABLA: TALLER_SESIONES
-- ============================================================================
CREATE TABLE IF NOT EXISTS taller_sesiones (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    taller_id INTEGER NOT NULL,
    numero_sesion INTEGER,
    titulo_sesion VARCHAR(255),
    descripcion_sesion TEXT,
    fecha_sesion DATE NOT NULL,
    hora_inicio TIME,
    duracion_minutos INTEGER DEFAULT 60,
    ubicacion_online VARCHAR(500),
    ubicacion_presencial VARCHAR(500),
    capacidad_actual INTEGER DEFAULT 0,
    FOREIGN KEY (taller_id) REFERENCES talleres_grupales(id) ON DELETE CASCADE ON UPDATE CASCADE
);

-- ============================================================================
-- TABLA: INSCRIPCION_TALLER
-- ============================================================================
CREATE TABLE IF NOT EXISTS inscripcion_taller (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id INTEGER NOT NULL,
    taller_id INTEGER NOT NULL,
    sesion_id INTEGER,
    fecha_inscripcion TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    estado VARCHAR(20) CHECK (estado IN ('inscrito', 'completado', 'abandonado', 'suspendido')) DEFAULT 'inscrito',
    monto_pagado DECIMAL(10,2),
    CONSTRAINT uk_usuario_taller UNIQUE (usuario_id, taller_id),
    FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (taller_id) REFERENCES talleres_grupales(id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (sesion_id) REFERENCES taller_sesiones(id) ON DELETE SET NULL ON UPDATE CASCADE
);

-- ============================================================================
-- TABLA: ASISTENCIA_TALLER
-- ============================================================================
CREATE TABLE IF NOT EXISTS asistencia_taller (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inscripcion_id INTEGER NOT NULL,
    sesion_id INTEGER NOT NULL,
    asistio BOOLEAN DEFAULT FALSE,
    fecha_registro TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_inscripcion_sesion UNIQUE (inscripcion_id, sesion_id),
    FOREIGN KEY (inscripcion_id) REFERENCES inscripcion_taller(id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (sesion_id) REFERENCES taller_sesiones(id) ON DELETE CASCADE ON UPDATE CASCADE
);

-- ============================================================================
-- TABLA: PAGOS
-- ============================================================================
CREATE TABLE IF NOT EXISTS pagos (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id INTEGER NOT NULL,
    tipo_pago VARCHAR(20) CHECK (tipo_pago IN ('sesion_profesional', 'taller', 'recurso_premium', 'suscripcion')),
    referencia_id INTEGER,
    monto DECIMAL(10,2) NOT NULL,
    moneda VARCHAR(3) DEFAULT 'USD',
    estado_pago VARCHAR(20) CHECK (estado_pago IN ('pendiente', 'pagado', 'fallido', 'reembolsado')) DEFAULT 'pendiente',
    metodo_pago VARCHAR(20) CHECK (metodo_pago IN ('tarjeta_credito', 'paypal', 'transferencia', 'otro')),
    referencia_transaccion VARCHAR(255),
    fecha_pago TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    fecha_reembolso TIMESTAMPTZ,
    notas TEXT,
    FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE ON UPDATE CASCADE
);

-- ============================================================================
-- TABLA: AFILIADOS
-- ============================================================================
CREATE TABLE IF NOT EXISTS afiliados (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id INTEGER NOT NULL,
    recurso_id INTEGER,
    plataforma_afiliado VARCHAR(100),
    codigo_afiliado VARCHAR(255),
    url_afiliado_personalizada VARCHAR(500),
    comision_porcentaje DECIMAL(5,2) DEFAULT 5.00,
    ingresos_generados DECIMAL(10,2) DEFAULT 0,
    estado VARCHAR(20) CHECK (estado IN ('activo', 'pausado', 'inactivo')) DEFAULT 'activo',
    fecha_creacion TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================================
-- TABLA: SUPERVISIONES
-- ============================================================================
CREATE TABLE IF NOT EXISTS supervisiones (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supervisor_id INTEGER NOT NULL,
    profesional_id INTEGER NOT NULL,
    tipo_supervision VARCHAR(20) CHECK (tipo_supervision IN ('individual', 'grupal', 'evaluacion')) DEFAULT 'individual',
    fecha_supervision DATE NOT NULL,
    duracion_minutos INTEGER,
    contenido TEXT,
    observaciones TEXT,
    areas_mejora TEXT,
    proxima_supervision DATE,
    fecha_creacion TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (supervisor_id) REFERENCES profesionales(id) ON DELETE RESTRICT ON UPDATE CASCADE,
    FOREIGN KEY (profesional_id) REFERENCES profesionales(id) ON DELETE CASCADE ON UPDATE CASCADE
);

-- ============================================================================
-- TABLA: CONVENIOS
-- ============================================================================
CREATE TABLE IF NOT EXISTS convenios (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_institucion VARCHAR(255) NOT NULL,
    tipo_convenio VARCHAR(20) CHECK (tipo_convenio IN ('clinica', 'universidad', 'centro_salud', 'organizacion_social', 'otro')),
    descripcion TEXT,
    contacto_nombre VARCHAR(255),
    contacto_email VARCHAR(255),
    contacto_telefono VARCHAR(20),
    beneficios_para_usuarios TEXT,
    beneficios_para_institucion TEXT,
    estado VARCHAR(20) CHECK (estado IN ('activo', 'pendiente', 'suspendido', 'finalizado')) DEFAULT 'pendiente',
    fecha_inicio DATE,
    fecha_fin DATE,
    fecha_creacion TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================================
-- TABLA: BITACORA_AUDITORIA
-- ============================================================================
CREATE TABLE IF NOT EXISTS bitacora_auditoria (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id INTEGER,
    tipo_accion VARCHAR(100) NOT NULL,
    tabla_afectada VARCHAR(100) NOT NULL,
    registro_id INTEGER,
    descripcion TEXT,
    datos_anteriores JSONB,
    datos_nuevos JSONB,
    ip_address VARCHAR(45),
    fecha_accion TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE SET NULL ON UPDATE CASCADE
);

-- ============================================================================
-- CREAR ÍNDICES ADICIONALES PARA OPTIMIZACIÓN
-- ============================================================================
CREATE INDEX IF NOT EXISTS idx_usuarios_estado_fecha ON usuarios(estado, fecha_creacion);
CREATE INDEX IF NOT EXISTS idx_profesionales_tarifa ON profesionales(tarifa_sesion, estado);
CREATE INDEX IF NOT EXISTS idx_pagos_usuario_fecha ON pagos(usuario_id, fecha_pago);
CREATE INDEX IF NOT EXISTS idx_foro_temas_forum_fecha ON foro_temas(forum_id, fecha_creacion);
CREATE INDEX IF NOT EXISTS idx_diario_usuario_mes ON diario_emocional (usuario_id, (date_trunc('month', fecha_entrada::timestamp)));
CREATE INDEX IF NOT EXISTS idx_sesiones_medicas_usuario ON sesiones_medicas(usuario_id, fecha_sesion);



-- ============================================================================
-- ÍNDICES CONVERTIDOS DESDE MYSQL
-- ============================================================================
CREATE INDEX IF NOT EXISTS idx_roles_nombre ON roles (nombre);
CREATE INDEX IF NOT EXISTS idx_roles_estado ON roles (estado);
CREATE INDEX IF NOT EXISTS idx_usuarios_email ON usuarios (email);
CREATE INDEX IF NOT EXISTS idx_usuarios_estado ON usuarios (estado);
CREATE INDEX IF NOT EXISTS idx_usuarios_fecha_creacion ON usuarios (fecha_creacion);
CREATE INDEX IF NOT EXISTS idx_usuario_roles_usuario_id ON usuario_roles (usuario_id);
CREATE INDEX IF NOT EXISTS idx_usuario_roles_rol_id ON usuario_roles (rol_id);
CREATE INDEX IF NOT EXISTS idx_datos_iniciales_usuario_estres ON datos_iniciales_usuario (tiene_estres);
CREATE INDEX IF NOT EXISTS idx_datos_iniciales_usuario_tristeza ON datos_iniciales_usuario (tiene_tristeza);
CREATE INDEX IF NOT EXISTS idx_especialidades_nombre ON especialidades (nombre);
CREATE INDEX IF NOT EXISTS idx_profesionales_estado ON profesionales (estado);
CREATE INDEX IF NOT EXISTS idx_profesionales_especialidad ON profesionales (especialidad_principal_id);
CREATE INDEX IF NOT EXISTS idx_profesionales_es_voluntario ON profesionales (es_voluntario);
CREATE INDEX IF NOT EXISTS idx_disponibilidad_usuario_id ON disponibilidad (usuario_id);
CREATE INDEX IF NOT EXISTS idx_disponibilidad_dia_semana ON disponibilidad (dia_semana);
CREATE INDEX IF NOT EXISTS idx_problemas_emocionales_nombre ON problemas_emocionales (nombre);
CREATE INDEX IF NOT EXISTS idx_personajes_tipo ON personajes (tipo_personaje);
CREATE INDEX IF NOT EXISTS idx_personajes_estado ON personajes (estado);
CREATE INDEX IF NOT EXISTS idx_personaje_problema_personaje_id ON personaje_problema (personaje_id);
CREATE INDEX IF NOT EXISTS idx_personaje_problema_problema_id ON personaje_problema (problema_id);
CREATE INDEX IF NOT EXISTS idx_diario_emocional_usuario_fecha ON diario_emocional (usuario_id, fecha_entrada);
CREATE INDEX IF NOT EXISTS idx_diario_emocional_estado_privacidad ON diario_emocional (estado_privacidad);
CREATE INDEX IF NOT EXISTS idx_emocion_dia_diario_id ON emocion_dia (diario_id);
CREATE INDEX IF NOT EXISTS idx_emocion_dia_personaje_id ON emocion_dia (personaje_id);
CREATE INDEX IF NOT EXISTS idx_categorias_recursos_nombre ON categorias_recursos (nombre);
CREATE INDEX IF NOT EXISTS idx_recursos_digitales_tipo ON recursos_digitales (tipo_contenido);
CREATE INDEX IF NOT EXISTS idx_recursos_digitales_estado ON recursos_digitales (estado);
CREATE INDEX IF NOT EXISTS idx_recursos_digitales_es_premium ON recursos_digitales (es_premium);
CREATE INDEX IF NOT EXISTS idx_recurso_categoria_recurso_id ON recurso_categoria (recurso_id);
CREATE INDEX IF NOT EXISTS idx_recurso_categoria_categoria_id ON recurso_categoria (categoria_id);
CREATE INDEX IF NOT EXISTS idx_recursos_descargados_usuario_id ON recursos_descargados (usuario_id);
CREATE INDEX IF NOT EXISTS idx_recursos_descargados_fecha_descarga ON recursos_descargados (fecha_descarga);
CREATE INDEX IF NOT EXISTS idx_profesional_especialidad_profesional_id ON profesional_especialidad (profesional_id);
CREATE INDEX IF NOT EXISTS idx_sesiones_medicas_usuario_id ON sesiones_medicas (usuario_id);
CREATE INDEX IF NOT EXISTS idx_sesiones_medicas_profesional_id ON sesiones_medicas (profesional_id);
CREATE INDEX IF NOT EXISTS idx_sesiones_medicas_fecha_sesion ON sesiones_medicas (fecha_sesion);
CREATE INDEX IF NOT EXISTS idx_sesiones_medicas_estado_sesion ON sesiones_medicas (estado_sesion);
CREATE INDEX IF NOT EXISTS idx_valoraciones_profesional_profesional_id ON valoraciones_profesional (profesional_id);
CREATE INDEX IF NOT EXISTS idx_valoraciones_profesional_puntuacion ON valoraciones_profesional (puntuacion);
CREATE INDEX IF NOT EXISTS idx_logros_tipo_logro ON logros (tipo_logro);
CREATE INDEX IF NOT EXISTS idx_usuario_logros_usuario_id ON usuario_logros (usuario_id);
CREATE INDEX IF NOT EXISTS idx_usuario_logros_fecha_desbloqueado ON usuario_logros (fecha_desbloqueado);
CREATE INDEX IF NOT EXISTS idx_foros_tematicos_nombre ON foros_tematicos (nombre);
CREATE INDEX IF NOT EXISTS idx_foros_tematicos_estado ON foros_tematicos (estado);
CREATE INDEX IF NOT EXISTS idx_foro_temas_forum_id ON foro_temas (forum_id);
CREATE INDEX IF NOT EXISTS idx_foro_temas_fecha_creacion ON foro_temas (fecha_creacion);
CREATE INDEX IF NOT EXISTS idx_foro_respuestas_tema_id ON foro_respuestas (tema_id);
CREATE INDEX IF NOT EXISTS idx_foro_respuestas_usuario_id ON foro_respuestas (usuario_id);
CREATE INDEX IF NOT EXISTS idx_foro_respuestas_es_solucion ON foro_respuestas (es_solucion);
CREATE INDEX IF NOT EXISTS idx_moderadores_forum_id ON moderadores (forum_id);
CREATE INDEX IF NOT EXISTS idx_reportes_contenido_estado ON reportes_contenido (estado);
CREATE INDEX IF NOT EXISTS idx_reportes_contenido_fecha_reporte ON reportes_contenido (fecha_reporte);
CREATE INDEX IF NOT EXISTS idx_talleres_grupales_estado ON talleres_grupales (estado);
CREATE INDEX IF NOT EXISTS idx_talleres_grupales_tipo_taller ON talleres_grupales (tipo_taller);
CREATE INDEX IF NOT EXISTS idx_taller_sesiones_taller_id ON taller_sesiones (taller_id);
CREATE INDEX IF NOT EXISTS idx_taller_sesiones_fecha_sesion ON taller_sesiones (fecha_sesion);
CREATE INDEX IF NOT EXISTS idx_inscripcion_taller_usuario_id ON inscripcion_taller (usuario_id);
CREATE INDEX IF NOT EXISTS idx_inscripcion_taller_estado ON inscripcion_taller (estado);
CREATE INDEX IF NOT EXISTS idx_asistencia_taller_sesion_id ON asistencia_taller (sesion_id);
CREATE INDEX IF NOT EXISTS idx_pagos_usuario_id ON pagos (usuario_id);
CREATE INDEX IF NOT EXISTS idx_pagos_estado_pago ON pagos (estado_pago);
CREATE INDEX IF NOT EXISTS idx_pagos_fecha_pago ON pagos (fecha_pago);
CREATE INDEX IF NOT EXISTS idx_afiliados_usuario_id ON afiliados (usuario_id);
CREATE INDEX IF NOT EXISTS idx_afiliados_estado ON afiliados (estado);
CREATE INDEX IF NOT EXISTS idx_supervisiones_supervisor_id ON supervisiones (supervisor_id);
CREATE INDEX IF NOT EXISTS idx_supervisiones_profesional_id ON supervisiones (profesional_id);
CREATE INDEX IF NOT EXISTS idx_supervisiones_fecha_supervision ON supervisiones (fecha_supervision);
CREATE INDEX IF NOT EXISTS idx_convenios_estado ON convenios (estado);
CREATE INDEX IF NOT EXISTS idx_bitacora_auditoria_usuario_id ON bitacora_auditoria (usuario_id);
CREATE INDEX IF NOT EXISTS idx_bitacora_auditoria_tabla_afectada ON bitacora_auditoria (tabla_afectada);
CREATE INDEX IF NOT EXISTS idx_bitacora_auditoria_fecha_accion ON bitacora_auditoria (fecha_accion);
CREATE INDEX IF NOT EXISTS idx_bitacora_auditoria_tipo_accion ON bitacora_auditoria (tipo_accion);
CREATE INDEX IF NOT EXISTS idx_usuarios_nombres ON usuarios USING GIN (to_tsvector('spanish', coalesce(nombres, '') || ' ' || coalesce(apellidos, '')));
CREATE INDEX IF NOT EXISTS idx_personajes_nombre ON personajes USING GIN (to_tsvector('spanish', coalesce(nombre, '') || ' ' || coalesce(descripcion, '')));
CREATE INDEX IF NOT EXISTS idx_recursos_digitales_titulo_descripcion ON recursos_digitales USING GIN (to_tsvector('spanish', coalesce(titulo, '') || ' ' || coalesce(descripcion, '')));
CREATE INDEX IF NOT EXISTS idx_foro_temas_titulo_contenido ON foro_temas USING GIN (to_tsvector('spanish', coalesce(titulo, '') || ' ' || coalesce(contenido, '')));
CREATE INDEX IF NOT EXISTS idx_talleres_grupales_titulo ON talleres_grupales USING GIN (to_tsvector('spanish', coalesce(titulo, '')));
CREATE INDEX IF NOT EXISTS idx_convenios_nombre ON convenios USING GIN (to_tsvector('spanish', coalesce(nombre_institucion, '')));

-- ============================================================================
-- TRIGGERS PARA FECHAS DE ACTUALIZACIÓN
-- ============================================================================
CREATE OR REPLACE FUNCTION fn_usuarios_fecha_actualizacion()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.fecha_actualizacion = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_usuarios_fecha_actualizacion ON usuarios;
CREATE TRIGGER trg_usuarios_fecha_actualizacion
BEFORE UPDATE ON usuarios
FOR EACH ROW EXECUTE FUNCTION fn_usuarios_fecha_actualizacion();
CREATE OR REPLACE FUNCTION fn_profesionales_fecha_actualizacion()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.fecha_actualizacion = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_profesionales_fecha_actualizacion ON profesionales;
CREATE TRIGGER trg_profesionales_fecha_actualizacion
BEFORE UPDATE ON profesionales
FOR EACH ROW EXECUTE FUNCTION fn_profesionales_fecha_actualizacion();
CREATE OR REPLACE FUNCTION fn_personajes_fecha_actualizacion()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.fecha_actualizacion = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_personajes_fecha_actualizacion ON personajes;
CREATE TRIGGER trg_personajes_fecha_actualizacion
BEFORE UPDATE ON personajes
FOR EACH ROW EXECUTE FUNCTION fn_personajes_fecha_actualizacion();
CREATE OR REPLACE FUNCTION fn_diario_emocional_actualizado_en()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.actualizado_en = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_diario_emocional_actualizado_en ON diario_emocional;
CREATE TRIGGER trg_diario_emocional_actualizado_en
BEFORE UPDATE ON diario_emocional
FOR EACH ROW EXECUTE FUNCTION fn_diario_emocional_actualizado_en();
CREATE OR REPLACE FUNCTION fn_recursos_digitales_fecha_actualizacion()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.fecha_actualizacion = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_recursos_digitales_fecha_actualizacion ON recursos_digitales;
CREATE TRIGGER trg_recursos_digitales_fecha_actualizacion
BEFORE UPDATE ON recursos_digitales
FOR EACH ROW EXECUTE FUNCTION fn_recursos_digitales_fecha_actualizacion();
CREATE OR REPLACE FUNCTION fn_foro_temas_fecha_ultima_actividad()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.fecha_ultima_actividad = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_foro_temas_fecha_ultima_actividad ON foro_temas;
CREATE TRIGGER trg_foro_temas_fecha_ultima_actividad
BEFORE UPDATE ON foro_temas
FOR EACH ROW EXECUTE FUNCTION fn_foro_temas_fecha_ultima_actividad();
CREATE OR REPLACE FUNCTION fn_foro_respuestas_fecha_actualizacion()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.fecha_actualizacion = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_foro_respuestas_fecha_actualizacion ON foro_respuestas;
CREATE TRIGGER trg_foro_respuestas_fecha_actualizacion
BEFORE UPDATE ON foro_respuestas
FOR EACH ROW EXECUTE FUNCTION fn_foro_respuestas_fecha_actualizacion();

-- ============================================================================
-- FORMULARIOS DE ESTADO
-- ============================================================================
CREATE TABLE IF NOT EXISTS preguntas_estado (
    id_pregunta BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    texto_pregunta TEXT NOT NULL,
    orden SMALLINT NOT NULL CHECK (orden BETWEEN 1 AND 5),
    activa BOOLEAN NOT NULL DEFAULT TRUE,
    tipo_formulario VARCHAR(30) NOT NULL
        CHECK (tipo_formulario IN ('REGISTRO', 'RETROALIMENTACION_SESION')),
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_preguntas_estado_tipo_orden UNIQUE (tipo_formulario, orden)
);

CREATE TABLE IF NOT EXISTS opciones_estado (
    id_opcion BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(30) NOT NULL UNIQUE
        CHECK (codigo IN ('MUY_BIEN', 'BIEN', 'MAS_O_MENOS', 'MAL', 'BASTANTE_MAL')),
    nombre VARCHAR(50) NOT NULL UNIQUE,
    valor_numerico SMALLINT NOT NULL UNIQUE CHECK (valor_numerico BETWEEN 1 AND 5),
    orden SMALLINT NOT NULL UNIQUE CHECK (orden BETWEEN 1 AND 5),
    activa BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS formularios_estado (
    id_formulario BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id INTEGER NOT NULL,
    sesion_medica_id INTEGER,
    tipo_formulario VARCHAR(30) NOT NULL
        CHECK (tipo_formulario IN ('REGISTRO', 'RETROALIMENTACION_SESION')),
    estado VARCHAR(20) NOT NULL DEFAULT 'PENDIENTE'
        CHECK (estado IN ('PENDIENTE', 'RESPONDIDO', 'OMITIDO')),
    fecha_inicio TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_respuesta TIMESTAMPTZ,
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_eliminacion TIMESTAMPTZ,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT fk_formulario_estado_usuario
        FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_formulario_estado_sesion
        FOREIGN KEY (sesion_medica_id) REFERENCES sesiones_medicas(id) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT ck_formulario_sesion_tipo CHECK (
        (tipo_formulario = 'REGISTRO' AND sesion_medica_id IS NULL)
        OR (tipo_formulario = 'RETROALIMENTACION_SESION' AND sesion_medica_id IS NOT NULL)
    )
);

CREATE TABLE IF NOT EXISTS respuestas_estado (
    id_respuesta BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_formulario BIGINT NOT NULL,
    id_pregunta BIGINT NOT NULL,
    id_opcion BIGINT NOT NULL,
    fecha_respuesta TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_respuesta_formulario_pregunta UNIQUE (id_formulario, id_pregunta),
    CONSTRAINT fk_respuesta_formulario
        FOREIGN KEY (id_formulario) REFERENCES formularios_estado(id_formulario) ON DELETE RESTRICT,
    CONSTRAINT fk_respuesta_pregunta
        FOREIGN KEY (id_pregunta) REFERENCES preguntas_estado(id_pregunta) ON DELETE RESTRICT,
    CONSTRAINT fk_respuesta_opcion
        FOREIGN KEY (id_opcion) REFERENCES opciones_estado(id_opcion) ON DELETE RESTRICT
);

-- La tabla de mensajes no existe en el esquema actual. mensaje_id se mantiene nullable
-- y sin clave foránea para evitar inventar o duplicar una entidad inexistente.
CREATE TABLE IF NOT EXISTS retroalimentaciones_sesion (
    id_retroalimentacion BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id INTEGER NOT NULL,
    profesional_id INTEGER NOT NULL,
    sesion_medica_id INTEGER NOT NULL,
    mensaje_id BIGINT,
    id_formulario_estado BIGINT,
    comentario TEXT,
    es_anonima BOOLEAN NOT NULL DEFAULT FALSE,
    visible_para_profesional BOOLEAN NOT NULL DEFAULT TRUE,
    visible_para_administrador BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_eliminacion TIMESTAMPTZ,
    activa BOOLEAN NOT NULL DEFAULT TRUE,
    version INTEGER NOT NULL DEFAULT 1 CHECK (version > 0),
    CONSTRAINT fk_retroalimentacion_usuario
        FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_retroalimentacion_profesional
        FOREIGN KEY (profesional_id) REFERENCES profesionales(id) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_retroalimentacion_sesion
        FOREIGN KEY (sesion_medica_id) REFERENCES sesiones_medicas(id) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_retroalimentacion_formulario
        FOREIGN KEY (id_formulario_estado) REFERENCES formularios_estado(id_formulario) ON DELETE RESTRICT,
    CONSTRAINT ck_retroalimentacion_contenido CHECK (
        comentario IS NOT NULL OR id_formulario_estado IS NOT NULL
    )
);

CREATE INDEX IF NOT EXISTS idx_preguntas_estado_activas
    ON preguntas_estado (tipo_formulario, activa, orden);
CREATE INDEX IF NOT EXISTS idx_formularios_estado_usuario
    ON formularios_estado (usuario_id, tipo_formulario, estado);
CREATE INDEX IF NOT EXISTS idx_formularios_estado_sesion
    ON formularios_estado (sesion_medica_id);
CREATE INDEX IF NOT EXISTS idx_respuestas_estado_formulario
    ON respuestas_estado (id_formulario);
CREATE INDEX IF NOT EXISTS idx_retroalimentacion_usuario
    ON retroalimentaciones_sesion (usuario_id);
CREATE INDEX IF NOT EXISTS idx_retroalimentacion_profesional
    ON retroalimentaciones_sesion (profesional_id);
CREATE INDEX IF NOT EXISTS idx_retroalimentacion_sesion
    ON retroalimentaciones_sesion (sesion_medica_id);
CREATE UNIQUE INDEX IF NOT EXISTS uk_retroalimentacion_activa_sesion_usuario
    ON retroalimentaciones_sesion (sesion_medica_id, usuario_id)
    WHERE activa = TRUE AND fecha_eliminacion IS NULL;

CREATE OR REPLACE FUNCTION fn_validar_maximo_preguntas_registro()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    total_activas INTEGER;
BEGIN
    IF NEW.tipo_formulario = 'REGISTRO' AND NEW.activa = TRUE THEN
        SELECT COUNT(*) INTO total_activas
        FROM preguntas_estado
        WHERE tipo_formulario = 'REGISTRO'
          AND activa = TRUE
          AND id_pregunta <> COALESCE(NEW.id_pregunta, -1);

        IF total_activas >= 5 THEN
            RAISE EXCEPTION 'No puede haber más de cinco preguntas activas para el formulario de registro';
        END IF;
    END IF;
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_maximo_preguntas_registro ON preguntas_estado;
CREATE TRIGGER trg_maximo_preguntas_registro
BEFORE INSERT OR UPDATE OF activa, tipo_formulario ON preguntas_estado
FOR EACH ROW EXECUTE FUNCTION fn_validar_maximo_preguntas_registro();

CREATE OR REPLACE FUNCTION fn_validar_retroalimentacion_sesion()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    sesion_usuario INTEGER;
    sesion_profesional INTEGER;
    formulario_usuario INTEGER;
    formulario_sesion INTEGER;
    formulario_tipo VARCHAR(30);
BEGIN
    SELECT usuario_id, profesional_id
      INTO sesion_usuario, sesion_profesional
      FROM sesiones_medicas
     WHERE id = NEW.sesion_medica_id;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'La sesión médica % no existe', NEW.sesion_medica_id;
    END IF;

    IF NEW.usuario_id <> sesion_usuario THEN
        RAISE EXCEPTION 'El paciente de la retroalimentación no coincide con el paciente de la sesión';
    END IF;

    IF NEW.profesional_id <> sesion_profesional THEN
        RAISE EXCEPTION 'El profesional de la retroalimentación no coincide con el profesional de la sesión';
    END IF;

    IF NEW.id_formulario_estado IS NOT NULL THEN
        SELECT usuario_id, sesion_medica_id, tipo_formulario
          INTO formulario_usuario, formulario_sesion, formulario_tipo
          FROM formularios_estado
         WHERE id_formulario = NEW.id_formulario_estado;

        IF NOT FOUND OR formulario_usuario <> NEW.usuario_id
           OR formulario_sesion <> NEW.sesion_medica_id
           OR formulario_tipo <> 'RETROALIMENTACION_SESION' THEN
            RAISE EXCEPTION 'El formulario de estado no corresponde al paciente y sesión indicados';
        END IF;
    END IF;

    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_validar_retroalimentacion_sesion ON retroalimentaciones_sesion;
CREATE TRIGGER trg_validar_retroalimentacion_sesion
BEFORE INSERT OR UPDATE ON retroalimentaciones_sesion
FOR EACH ROW EXECUTE FUNCTION fn_validar_retroalimentacion_sesion();

CREATE OR REPLACE FUNCTION fn_validar_respuesta_estado()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    formulario_tipo VARCHAR(30);
    pregunta_tipo VARCHAR(30);
    pregunta_activa BOOLEAN;
    opcion_activa BOOLEAN;
BEGIN
    SELECT tipo_formulario INTO formulario_tipo
      FROM formularios_estado WHERE id_formulario = NEW.id_formulario;
    SELECT tipo_formulario, activa INTO pregunta_tipo, pregunta_activa
      FROM preguntas_estado WHERE id_pregunta = NEW.id_pregunta;
    SELECT activa INTO opcion_activa
      FROM opciones_estado WHERE id_opcion = NEW.id_opcion;

    IF formulario_tipo IS NULL OR pregunta_tipo IS NULL OR opcion_activa IS NULL THEN
        RAISE EXCEPTION 'Formulario, pregunta u opción inexistente';
    END IF;
    IF formulario_tipo <> pregunta_tipo THEN
        RAISE EXCEPTION 'La pregunta no pertenece al tipo de formulario';
    END IF;
    IF pregunta_activa = FALSE OR opcion_activa = FALSE THEN
        RAISE EXCEPTION 'La pregunta y la opción deben estar activas';
    END IF;
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_validar_respuesta_estado ON respuestas_estado;
CREATE TRIGGER trg_validar_respuesta_estado
BEFORE INSERT OR UPDATE ON respuestas_estado
FOR EACH ROW EXECUTE FUNCTION fn_validar_respuesta_estado();

CREATE OR REPLACE FUNCTION fn_actualizar_fecha_formularios_estado()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    NEW.fecha_actualizacion = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$;
DROP TRIGGER IF EXISTS trg_actualizar_formularios_estado ON formularios_estado;
CREATE TRIGGER trg_actualizar_formularios_estado
BEFORE UPDATE ON formularios_estado
FOR EACH ROW EXECUTE FUNCTION fn_actualizar_fecha_formularios_estado();

CREATE OR REPLACE FUNCTION fn_actualizar_fecha_retroalimentacion()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    NEW.fecha_actualizacion = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$;
DROP TRIGGER IF EXISTS trg_actualizar_retroalimentacion ON retroalimentaciones_sesion;
CREATE TRIGGER trg_actualizar_retroalimentacion
BEFORE UPDATE ON retroalimentaciones_sesion
FOR EACH ROW EXECUTE FUNCTION fn_actualizar_fecha_retroalimentacion();

INSERT INTO opciones_estado (codigo, nombre, valor_numerico, orden, activa) VALUES
('MUY_BIEN', 'Muy bien', 5, 1, TRUE),
('BIEN', 'Bien', 4, 2, TRUE),
('MAS_O_MENOS', 'Más o menos', 3, 3, TRUE),
('MAL', 'Mal', 2, 4, TRUE),
('BASTANTE_MAL', 'Bastante mal', 1, 5, TRUE)
ON CONFLICT (codigo) DO NOTHING;

INSERT INTO preguntas_estado (texto_pregunta, orden, activa, tipo_formulario) VALUES
('¿Cómo te has sentido emocionalmente durante los últimos días?', 1, TRUE, 'REGISTRO'),
('¿Cómo ha estado tu nivel de energía?', 2, TRUE, 'REGISTRO'),
('¿Cómo ha estado tu calidad de sueño?', 3, TRUE, 'REGISTRO'),
('¿Cómo has manejado el estrés o la ansiedad?', 4, TRUE, 'REGISTRO'),
('¿Cómo te has sentido en tus actividades diarias?', 5, TRUE, 'REGISTRO')
ON CONFLICT (tipo_formulario, orden) DO NOTHING;

-- Preguntas de retroalimentación iniciales. Pueden administrarse desde la base de datos.
INSERT INTO preguntas_estado (texto_pregunta, orden, activa, tipo_formulario) VALUES
('¿Cómo te sientes después de la sesión?', 1, TRUE, 'RETROALIMENTACION_SESION'),
('¿Qué tan útil fue la sesión para comprender lo que estás sintiendo?', 2, TRUE, 'RETROALIMENTACION_SESION'),
('¿Cómo se encuentra tu nivel de tranquilidad después de la sesión?', 3, TRUE, 'RETROALIMENTACION_SESION')
ON CONFLICT (tipo_formulario, orden) DO NOTHING;

-- Vistas de validación no destructivas.
CREATE OR REPLACE VIEW vw_validacion_formularios_estado AS
SELECT
    f.id_formulario,
    f.usuario_id,
    f.sesion_medica_id,
    f.tipo_formulario,
    f.estado,
    COUNT(r.id_respuesta) AS total_respuestas,
    COUNT(DISTINCT r.id_pregunta) AS preguntas_distintas,
    CASE
        WHEN COUNT(r.id_respuesta) = COUNT(DISTINCT r.id_pregunta) THEN 'CORRECTO'
        ELSE 'DUPLICADOS'
    END AS estado_validacion
FROM formularios_estado f
LEFT JOIN respuestas_estado r ON r.id_formulario = f.id_formulario
GROUP BY f.id_formulario;

CREATE OR REPLACE VIEW vw_validacion_retroalimentaciones AS
SELECT
    r.id_retroalimentacion,
    r.sesion_medica_id,
    r.usuario_id,
    r.profesional_id,
    CASE
        WHEN s.id IS NULL THEN 'SESION_INEXISTENTE'
        WHEN s.usuario_id <> r.usuario_id THEN 'PACIENTE_NO_COINCIDE'
        WHEN s.profesional_id <> r.profesional_id THEN 'PROFESIONAL_NO_COINCIDE'
        ELSE 'CORRECTO'
    END AS estado_validacion
FROM retroalimentaciones_sesion r
LEFT JOIN sesiones_medicas s ON s.id = r.sesion_medica_id;

-- ============================================================================
-- INSERTAR DATOS DE EJEMPLO AMPLIADOS
-- ============================================================================

-- Insertar roles
INSERT INTO roles (nombre, descripcion, permisos_json, estado) VALUES
('usuario', 'Usuario regular de la plataforma', jsonb_build_object('crear_posts', true, 'comentar', true, 'leer_recursos', true), 'activo'),
('profesional', 'Profesional de salud (psicólogo, coach, etc)', jsonb_build_object('crear_sesiones', true, 'ver_fichas', true, 'crear_recursos', true), 'activo'),
('voluntario', 'Profesional voluntario con sesiones limitadas', jsonb_build_object('crear_sesiones', true, 'sesiones_max', 2), 'activo'),
('moderador', 'Moderador de comunidad y foros', jsonb_build_object('eliminar_contenido', true, 'bannear_usuarios', true), 'activo'),
('admin', 'Administrador del sistema', jsonb_build_object('all_permissions', true), 'activo'),
('supervisor', 'Supervisor de profesionales', jsonb_build_object('supervisar', true, 'evaluar', true), 'activo')
ON CONFLICT DO NOTHING;

-- Insertar usuarios (expandido)
INSERT INTO usuarios (email, password_hash, nombres, apellidos, fecha_nacimiento, genero, ciudad, estado) VALUES
('juan.garcia@example.com', '$2b$10$abcdefghijklmnopqrstuvwxyz', 'Juan', 'García', '1990-05-15', 'masculino', 'Santiago', 'activo'),
('maria.lopez@example.com', '$2b$10$abcdefghijklmnopqrstuvwxyz', 'María', 'López', '1995-08-22', 'femenino', 'Valparaíso', 'activo'),
('carlos.rodriguez@example.com', '$2b$10$abcdefghijklmnopqrstuvwxyz', 'Carlos', 'Rodríguez', '1988-03-10', 'masculino', 'Concepción', 'activo'),
('ana.martinez@example.com', '$2b$10$abcdefghijklmnopqrstuvwxyz', 'Ana', 'Martínez', '1985-07-18', 'femenino', 'Santiago', 'activo'),
('luis.perez@example.com', '$2b$10$abcdefghijklmnopqrstuvwxyz', 'Luis', 'Pérez', '1992-11-30', 'masculino', 'La Florida', 'activo'),
('sofia.diaz@example.com', '$2b$10$abcdefghijklmnopqrstuvwxyz', 'Sofía', 'Díaz', '1998-02-14', 'femenino', 'Ñuñoa', 'activo'),
('diego.torres@example.com', '$2b$10$abcdefghijklmnopqrstuvwxyz', 'Diego', 'Torres', '1987-09-05', 'masculino', 'Providencia', 'activo'),
('rosa.flores@example.com', '$2b$10$abcdefghijklmnopqrstuvwxyz', 'Rosa', 'Flores', '1993-06-20', 'femenino', 'Vitacura', 'activo'),
('pablo.silva@example.com', '$2b$10$abcdefghijklmnopqrstuvwxyz', 'Pablo', 'Silva', '1989-01-12', 'masculino', 'Carabineros', 'activo'),
('laura.morales@example.com', '$2b$10$abcdefghijklmnopqrstuvwxyz', 'Laura', 'Morales', '1996-04-08', 'femenino', 'Maipú', 'activo'),
('dr.alberto.silva@example.com', '$2b$10$abcdefghijklmnopqrstuvwxyz', 'Alberto', 'Silva', '1970-12-05', 'masculino', 'Santiago', 'activo'),
('coach.ana.terapia@example.com', '$2b$10$abcdefghijklmnopqrstuvwxyz', 'Ana Cecilia', 'Terapista', '1981-07-18', 'femenino', 'Santiago', 'activo'),
('psic.gonzalo@example.com', '$2b$10$abcdefghijklmnopqrstuvwxyz', 'Gonzalo', 'Ramírez', '1975-03-22', 'masculino', 'Las Condes', 'activo'),
('menta.carolina@example.com', '$2b$10$abcdefghijklmnopqrstuvwxyz', 'Carolina', 'Mendoza', '1988-10-15', 'femenino', 'Independencia', 'activo')
ON CONFLICT DO NOTHING;

-- Asignar roles a usuarios
INSERT INTO usuario_roles (usuario_id, rol_id) VALUES
(1, 1), (2, 1), (3, 1), (4, 1), (5, 1),
(6, 1), (7, 1), (8, 1), (9, 1), (10, 1),
(11, 2), (12, 2), (13, 2), (14, 2)
ON CONFLICT DO NOTHING;

-- Insertar datos iniciales de usuarios
INSERT INTO datos_iniciales_usuario (usuario_id, tiene_estres, tiene_tristeza, se_siente_desorientado, trabaja_actualmente, tiene_red_apoyo) VALUES
(1, TRUE, FALSE, TRUE, TRUE, TRUE),
(2, TRUE, TRUE, FALSE, TRUE, TRUE),
(3, FALSE, FALSE, TRUE, FALSE, FALSE),
(4, TRUE, FALSE, FALSE, TRUE, TRUE),
(5, FALSE, TRUE, TRUE, TRUE, FALSE),
(6, TRUE, TRUE, TRUE, TRUE, TRUE),
(7, FALSE, FALSE, FALSE, FALSE, TRUE),
(8, TRUE, FALSE, TRUE, TRUE, TRUE),
(9, FALSE, TRUE, FALSE, FALSE, FALSE),
(10, TRUE, TRUE, FALSE, TRUE, TRUE)
ON CONFLICT DO NOTHING;

-- Insertar problemas emocionales
INSERT INTO problemas_emocionales (nombre, descripcion) VALUES
('Ansiedad', 'Preocupación excesiva y persistente'),
('Estrés', 'Tensión emocional por presiones'),
('Soledad', 'Sentimiento de aislamiento y desconexión'),
('Duelo', 'Pérdida y dolor emocional'),
('Baja autoestima', 'Falta de confianza en uno mismo'),
('Crisis vocacional', 'Confusión sobre dirección profesional'),
('Burnout', 'Agotamiento emocional y laboral'),
('Crecimiento personal', 'Búsqueda de desarrollo y mejora')
ON CONFLICT DO NOTHING;

-- Insertar categorías de recursos
INSERT INTO categorias_recursos (nombre, descripcion) VALUES
('Gestión emocional', 'Recursos para manejar emociones'),
('Mindfulness', 'Técnicas de atención plena'),
('Autocuidado', 'Prácticas de cuidado personal'),
('Hábitos saludables', 'Desarrollo de hábitos positivos'),
('Equilibrio vida-trabajo', 'Balance entre personal y laboral'),
('Resiliencia', 'Capacidad de superación y recuperación'),
('Relaciones interpersonales', 'Mejora de vínculos con otros')
ON CONFLICT DO NOTHING;

-- Insertar recursos de ejemplo (expandido)
INSERT INTO recursos_digitales (titulo, descripcion, tipo_contenido, autor, es_premium, precio) VALUES
('Introducción a Mindfulness', 'Guía completa para principiantes en meditación', 'articulo', 'Sistema Bienestar', FALSE, NULL),
('Meditación diaria 10 minutos', 'Meditación guiada para relajación profunda', 'video', 'Coach Maya', TRUE, 9.99),
('Podcast: Vidas Transformadas', 'Historias inspiradoras de superación personal', 'podcast', 'Red Bienestar', FALSE, NULL),
('Manual de Gestión del Estrés', 'Técnicas prácticas y efectivas comprobadas', 'documento', 'Dr. Roberto', TRUE, 14.99),
('Infografía: 7 Hábitos Saludables', 'Guía visual de buenos hábitos cotidianos', 'infografia', 'Sistema Bienestar', FALSE, NULL),
('El Arte de la Resiliencia', 'Libro sobre cómo superar adversidades', 'libro', 'Patricia González', TRUE, 19.99),
('Yoga para la Ansiedad', 'Video tutorial de 30 minutos de yoga', 'video', 'Instructor Luis', FALSE, NULL),
('Relaciones Sanas', 'Artículo sobre comunicación efectiva', 'articulo', 'Psicóloga Carla', FALSE, NULL),
('Podcast: Bienestar Mental', 'Episodios semanales sobre salud mental', 'podcast', 'Dr. Sistema', TRUE, 4.99),
('Diario de Gratitud Digital', 'Aplicación web para registro diario', 'documento', 'Tech Wellness', FALSE, NULL)
ON CONFLICT DO NOTHING;

-- Insertar especialidades
INSERT INTO especialidades (nombre, descripcion) VALUES
('Psicología Clínica', 'Diagnóstico y tratamiento de trastornos'),
('Psicología Organizacional', 'Recursos humanos y bienestar laboral'),
('Coaching Vocacional', 'Orientación profesional y carrera'),
('Mindfulness', 'Meditación y atención plena'),
('Nutrición y Bienestar', 'Asesoramiento nutricional integral'),
('Terapia Complementaria', 'Terapias alternativas e integrativas'),
('Autoestima y Confianza', 'Desarrollo personal y seguridad'),
('Relaciones Interpersonales', 'Mejora de habilidades comunicativas')
ON CONFLICT DO NOTHING;

-- Insertar profesionales (expandido)
INSERT INTO profesionales (usuario_id, licencia_profesional, especialidad_principal_id, es_voluntario, tarifa_sesion, anos_experiencia) VALUES
(11, 'LC-12345', (SELECT id FROM especialidades WHERE nombre = 'Psicología Clínica' LIMIT 1), FALSE, 80.00, 15),
(12, 'LC-67890', (SELECT id FROM especialidades WHERE nombre = 'Mindfulness' LIMIT 1), FALSE, 60.00, 8),
(13, 'LC-54321', (SELECT id FROM especialidades WHERE nombre = 'Psicología Clínica' LIMIT 1), TRUE, 50.00, 5),
(14, 'LC-98765', (SELECT id FROM especialidades WHERE nombre = 'Psicología Organizacional' LIMIT 1), FALSE, 75.00, 10)
ON CONFLICT DO NOTHING;

-- Insertar logros
INSERT INTO logros (nombre, descripcion, tipo_logro, puntos) VALUES
('Primer Paso', 'Completa tu primer registro', 'registro', 10),
('Diario Activo', 'Escribe en el diario 7 días consecutivos', 'registro', 50),
('Miembro Activo', 'Participa en 10 publicaciones', 'participacion', 30),
('Explorador', 'Descubre 5 personajes diferentes', 'recursos', 20),
('Aprendiz', 'Completa tu primer taller', 'taller', 100),
('Maestro', 'Completa 5 talleres', 'taller', 250),
('Conectado', 'Consigue 5 conexiones en la comunidad', 'social', 40),
('Inspirador', 'Recibe 50 reacciones positivas', 'social', 75)
ON CONFLICT DO NOTHING;

-- Insertar foros temáticos
INSERT INTO foros_tematicos (nombre, descripcion, categoria) VALUES
('Ansiedad Universitaria', 'Espacio para estudiantes con estrés académico', 'salud_mental'),
('Gestión Emocional', 'Técnicas y estrategias para manejar emociones', 'desarrollo_personal'),
('TDAH en Adultos', 'Comunidad de apoyo para TDAH', 'salud_mental'),
('Autocuidado', 'Prácticas y hábitos de cuidado personal', 'bienestar'),
('Bienestar Laboral', 'Equilibrio entre trabajo y vida personal', 'trabajo'),
('Resiliencia y Superación', 'Historias y consejos sobre resiliencia', 'desarrollo_personal')
ON CONFLICT DO NOTHING;

-- Insertar personajes de ejemplo
INSERT INTO personajes (nombre, origen, tipo_personaje, descripcion) VALUES
('Clark Kent/Superman', 'DC Comics', 'ficticio', 'Superhéroe que lucha con su identidad dual y el peso de las responsabilidades'),
('Nelson Mandela', 'Historia', 'historico', 'Líder que superó 27 años de encarcelamiento'),
('Oprah Winfrey', 'Personajes Reales', 'celebridad', 'Emprendedora que superó pobreza y discriminación'),
('Elliot Alderson', 'Mr. Robot', 'serie', 'Personaje con ansiedad social que busca propósito y justicia'),
('Luffy', 'One Piece', 'anime', 'Pirata determinado que busca sus sueños a pesar de los obstáculos'),
('Walter White', 'Breaking Bad', 'serie', 'Hombre ordinario que enfrenta enfermedad y transformación personal')
ON CONFLICT DO NOTHING;

-- ============================================================================
-- AJUSTE DE SECUENCIAS DESPUÉS DE IMPORTAR IDS EXISTENTES
-- ============================================================================
DO $$
DECLARE
    rec RECORD;
    max_id BIGINT;
BEGIN
    FOR rec IN
        SELECT table_schema, table_name, column_name,
               pg_get_serial_sequence(format('%I.%I', table_schema, table_name), column_name) AS seq_name
        FROM information_schema.columns
        WHERE table_schema = current_schema()
          AND is_identity = 'YES'
    LOOP
        EXECUTE format('SELECT COALESCE(MAX(%I), 0) FROM %I.%I', rec.column_name, rec.table_schema, rec.table_name)
        INTO max_id;
        IF rec.seq_name IS NOT NULL THEN
            PERFORM setval(rec.seq_name, GREATEST(max_id, 1), max_id > 0);
        END IF;
    END LOOP;
END;
$$;

COMMIT;

-- ============================================================================
-- VERIFICACIÓN FINAL
-- ============================================================================
SELECT '✓ Base de datos versión 2.0 creada correctamente' AS mensaje;
SELECT 'Total de tablas: ' || COUNT(*) AS tabla_count 
FROM information_schema.tables 
WHERE table_schema = current_schema();

-- ============================================================================
